forum/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'forum.views.home', name='forum_home'),
    
    url(r'^ajax/prev_messages/$', 'forum.views.ajax_prev_messages', name='ajax_prev_messages'),
    url(ur'^admin/message/(?P<id>\d+)/delete/$', 'forum.views.message_delete', name='admin_message_delete'),
    url(r'^topic/(?P<id>\d+)/$', 'forum.views.topic', {'slug': ''}),
    url(ur'^topic/(?P<id>\d+)/(?P<slug>[\w\s-]+)/$', 'forum.views.topic', name='forum_topic'),
    
    url(ur'^thread/(?P<id>\d+)/(?P<slug>[\w\s-]+)/$', 'forum.views.thread', name='forum_thread'),
    url(ur'^topic/(?P<id>\d+)/thread/create/$', 'forum.views.create_thread', name='forum_create_thread'),
)

lib/grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
from django.conf.urls import patterns, url

# GRAPPELLI IMPORTS
from .views.related import RelatedLookup, M2MLookup, AutocompleteLookup
from .views.switch import switch_user


urlpatterns = patterns(
    '',

    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    url(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    url(r'^switch/user/(?P<object_id>\d+)/$', switch_user, name="grp_switch_user"),

    # GRAPPELLI DOM DOCUMENTATION
    # url(r'^grp-doc/change-form/', TemplateView.as_view(template_name='grp_doc/change_form.html'), name="grp_doc_change_form"),
    # url(r'^grp-doc/change-list/', TemplateView.as_view(template_name='grp_doc/change_list.html'), name="grp_doc_change_list"),
    # url(r'^grp-doc/admin-index/', TemplateView.as_view(template_name='grp_doc/admin_index.html'), name="grp_doc_admin_index"),

    # url(r'^grp-doc/tables/', TemplateView.as_view(template_name='grp_doc/tables.html'), name="grp_doc_tables"),

    # url(r'^grp-doc/pagination/', TemplateView.as_view(template_name='grp_doc/pagination.html'), name="grp_doc_pagination"),
    # url(r'^grp-doc/search-form/', TemplateView.as_view(template_name='grp_doc/search_form.html'), name="grp_doc_search_form"),
    # url(r'^grp-doc/filter/', TemplateView.as_view(template_name='grp_doc/filter.html'), name="grp_doc_filter"),
    # url(r'^grp-doc/date-hierarchy/', TemplateView.as_view(template_name='grp_doc/date_hierarchy.html'), name="grp_doc_date_hierarchy"),

    # url(r'^grp-doc/fieldsets/', TemplateView.as_view(template_name='grp_doc/fieldsets.html'), name="grp_doc_fieldsets"),
    # url(r'^grp-doc/errors/', TemplateView.as_view(template_name='grp_doc/errors.html'), name="grp_doc_errors"),
    # url(r'^grp-doc/form-fields/', TemplateView.as_view(template_name='grp_doc/form_fields.html'), name="grp_doc_form_fields"),
    # url(r'^grp-doc/submit-rows/', TemplateView.as_view(template_name='grp_doc/submit_rows.html'), name="grp_doc_submit_rows"),

    # url(r'^grp-doc/modules/', TemplateView.as_view(template_name='grp_doc/modules.html'), name="grp_doc_modules"),
    # url(r'^grp-doc/groups/', TemplateView.as_view(template_name='grp_doc/groups.html'), name="grp_doc_groups"),

    # url(r'^grp-doc/navigation/', TemplateView.as_view(template_name='grp_doc/navigation.html'), name="grp_doc_navigation"),
    # url(r'^grp-doc/context-navigation/', TemplateView.as_view(template_name='grp_doc/context_navigation.html'), name="grp_doc_context_navigation"),

    # url(r'^grp-doc/basic-page-structure/', TemplateView.as_view(template_name='grp_doc/basic_page_structure.html'), name="grp_doc_basic_page_structure"),

    # url(r'^grp-doc/tools/', TemplateView.as_view(template_name='grp_doc/tools.html'), name="grp_doc_tools"),
    # url(r'^grp-doc/object-tools/', TemplateView.as_view(template_name='grp_doc/object_tools.html'), name="grp_doc_object_tools"),

    # url(r'^grp-doc/mueller-grid-system-tests/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_tests.html'), name="grp_doc_mueller_grid_system_tests"),
    # url(r'^grp-doc/mueller-grid-system/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system.html'), name="grp_doc_mueller_grid_system"),
    # url(r'^grp-doc/mueller-grid-system-layouts/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_layouts.html'), name="grp_doc_mueller_grid_system_layouts"),

    # url(r'^grp-doc', TemplateView.as_view(template_name='grp_doc/index.html'), name="grp_doc"),

)

main/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^summernote/', include('lib.django_summernote.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    
    url(r'^store/$', 'main.views.store_page.main', name='store'),
    url(r'^store/delivery/$', 'main.views.store_page.delivery', name='store_delivery'),
    
    url(r'^basket/(?P<id>\d+)/toggle/$', 'main.views.basket.toggle', name='basket_toggle'),
    url(r'^basket/$', 'main.views.basket.main', name='basket'),
    
    url(r'^$', 'main.views.home', name='home'),
    
    url(r'^search/$', 'main.views.search', name='search'),
    url(r'^account/logout/$', 'main.views.logout', name='logout'),
    
    url(r'^category/(?P<id>\d+)/$', 'main.views.category.info', {'slug': '', 'other': False}),
    url(r'^category/(?P<id>\d+)/(?P<slug>[\w-]+)/$', 'main.views.category.info', {'other': False}, name='category', ),
    url(r'^category/(?P<id>\d+)/(?P<slug>[\w-]+)/other/$', 'main.views.category.info', {'other': True}),
    
    url(r'^brand/(?P<id>\d+)/$', 'main.views.brand.info', {'slug': ''}),
    url(r'^brand/(?P<id>\d+)/(?P<slug>[\w-]+)/$', 'main.views.brand.info', name='brand'),
    
    # url(r'^shop/list/$', 'main.views.shop.list', name='shop_list'),

    url(r'^shop/(?P<id>\d+)/reviews/$', 'main.views.shop.reviews', {'slug': ''}),
    url(r'^shop/(?P<id>\d+)/(?P<slug>[\w-]+)/reviews/$', 'main.views.shop.reviews', name='shop_reviews'),    
    
    url(r'^shop/(?P<id>\d+)/$', 'main.views.shop.info', {'slug': ''}),
    url(r'^shop/(?P<id>\d+)/(?P<slug>[\w-]+)/$', 'main.views.shop.info', name='shop'),
    
    url(r'^product/(?P<id>\d+)/ingredients/$', 'main.views.product.ingredients', {'slug': ''}),
    url(r'^product/(?P<id>\d+)/(?P<slug>[\w-]+)/ingredients/$', 'main.views.product.ingredients', name='product_ingredients'),
  
    url(r'^product/(?P<id>\d+)/reviews/$', 'main.views.product.reviews', {'slug': ''}),
    url(r'^product/(?P<id>\d+)/(?P<slug>[\w-]+)/reviews/$', 'main.views.product.reviews', name='product_reviews'),
  
    url(r'^product/(?P<id>\d+)/description/$', 'main.views.product.description', {'slug': ''}),
    url(r'^product/(?P<id>\d+)/(?P<slug>[\w-]+)/description/$', 'main.views.product.description', name='product_description'),
  
    url(r'^product/(?P<id>\d+)/$', 'main.views.product.prices', {'slug': ''}),
    url(r'^product/(?P<id>\d+)/(?P<slug>[\w-]+)/$', 'main.views.product.prices', name='product'),
  
    url(r'^jump/(?P<id>\d+)/$', 'main.views.product.item_jump', name='product_item_jump'),
    
    url(r'^shopping_list/clear/$', 'main.views.shopping_list.clear', name='shopping_list_clear'),
    url(r'^shopping_list/(?P<id>\d+)/toggle/$', 'main.views.shopping_list.toggle', name='shopping_list_toggle'),
    url(r'^shopping_list/$', 'main.views.shopping_list.main', name='shopping_list'),
    
	url(r'^admin/', include(admin.site.urls)),
	url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
	url(r'', include('social_auth.urls')),
)

qa/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'qa.views.list', name='qa_home'),
    url(r'^new/$', 'qa.views.list', name='qa_list'),
    url(r'^without_answer/$', 'qa.views.list', {'without_answer': True}, name='qa_list_without_answer'),
    url(r'^create/$', 'qa.views.create', name='qa_create'),
    url(r'^(?P<id>\d+)/subscribe/$', 'qa.views.subscribe', name='qa_subscribe'),
    url(r'^(?P<id>\d+)/unsubscribe/$', 'qa.views.unsubscribe', name='qa_unsubscribe'),
    url(r'^(?P<id>\d+)/$', 'qa.views.question_show', {'slug': ''}),
    url(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/$', 'qa.views.question_show', name='qa_question'),
    url(r'^(?P<qid>\d+)/select/(?P<aid>\d+)/$', 'qa.views.select_answer', name='qa_select_answer'),
)

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from unidecode import unidecode

from lib.mptt.models import MPTTModel, TreeForeignKey

def get_slug(name):
	return slugify(unidecode(name))

class Topic(MPTTModel):
	title = models.CharField(max_length=200)
	slug = models.CharField(max_length=200)
	created_at = models.DateTimeField(auto_now_add=True)
	parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

	def __unicode__(self):
		return self.title

	@property
	def topic_count(self):
		return self.get_descendant_count()

	@property
	def thread_count(self):
		return Thread.objects.filter(
			topic_id__in=[t.id for t in self.get_descendants(include_self=True)]
		).count()

	@property
	def last_message(self):
		if not hasattr(self, '_last_message'):
			threads = Thread.objects.filter(
				topic_id__in=[t.id for t in self.get_descendants(include_self=True)]
			)	
			messages = Message.objects\
				.filter(thread_id__in=[t.id for t in threads])\
				.order_by('-created_at')
			if len(messages):
				self._last_message = messages[0]
			else:
				self._last_message = None
		return self._last_message

	@property
	def message_count(self):
		threads = Thread.objects.filter(
			topic_id__in=[t.id for t in self.get_descendants(include_self=True)]
		)
		messages = Message.objects.filter(thread_id__in=[t.id for t in threads])
		
		return messages.count()

	def save(self, *args, **kwargs):
		self.slug = get_slug(self.title)
		super(Topic, self).save(*args, **kwargs)
		
class Thread(models.Model):
	topic = models.ForeignKey(Topic)
	title = models.CharField(max_length=200)
	slug = models.CharField(max_length=200)
	user = models.ForeignKey(User)
	created_at = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.title

	@property
	def message_count(self):
		return Message.objects.filter(thread=self).count()

	@property
	def last_message(self):
		if not hasattr(self, '_last_message'):
			messages = Message.objects\
				.filter(thread=self)\
				.order_by('-created_at')
			if len(messages):
				self._last_message = messages[0]
			else:
				self._last_message = None
		return self._last_message

	def save(self, *args, **kwargs):
		self.slug = get_slug(self.title)
		super(Thread, self).save(*args, **kwargs)

class Message(models.Model):
	thread = models.ForeignKey(Thread)
	user = models.ForeignKey(User)
	reply_to = models.ForeignKey('self',related_name='reply_to_reverse',null=True,default=None)
	root = models.ForeignKey('self',related_name='root_reverse',null=True,default=None)

	content = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)
	per_page = 10

	@property
	def last_replies(self):
		if not hasattr(self, '_last_replies'):
			self._last_replies = None
			
			messages = Message.objects.filter(root=self)
			count = messages.count()
			if count:
				messages = messages.order_by('-created_at')[:3][::-1]
				has_next = True if count > 3 else False
				end_index = min(self.per_page, count)
				self._last_replies = {
					'object_list': messages,
					'end_index': end_index,
					'has_next': has_next,
					'next_page_number': 1,
					'paginator': {'count': count},
				}
		return self._last_replies

forum/templates/forum/create_thread.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ topic.title }}{% endblock %}

{% block content %}
<div class="page-head">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>{{ topic.title }}</h2>
        <h4>создать тему</h4>
      </div>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        {% breadcrumbs_block %}

        {% load widget_tweaks %}
        <!-- Form Comment -->
        <div class="respond well">
        <!-- Form title -->
         <div class="title"><h4>Создать тему</h4></div>
         <!-- Comment form -->
         <div class="form">
           <form class="form-horizontal" method="post">
             {% csrf_token %}
             <div class="form-group">
               <label class="control-label col-md-3">Заголовок</label>
               <div class="col-md-6">
                {{ form.title|attr:"class:form-control" }}
                <p class="help-block">{{ form.title.errors }}</p>
               </div>
             </div>
             <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
               <button type="submit" class="btn btn-default">Создать</button>
               <button type="reset" class="btn btn-default">Сбросить</button>
              </div>
             </div>
           </form>
         </div>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

forum/templates/forum/message.html
{% load blog_tags %}
{% load staticfiles %}
{% load thumbnail %}

<a name="{{ m.id }}"></a>
{% user_profile m.user %}
<a class="pull-left" href="{% url 'user' m.user.id %}">
  <!-- Avatar -->
  {% thumbnail profile.avatar_image "60x60" crop="center" as im %}
      <img class="avatar" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
  {% endthumbnail %}
</a>

<!-- Author -->
<div class="comment-author">
  <a href="{% url 'user' m.user.id %}">{{ m.user.username }}</a>
  {% if request.user.is_authenticated and m.user_id != request.user.id %}
  <span class="answer"> - <a href="javascript:reply({{ m.id }}, '{{ m.user.username }}');">ответить</a></span>
  {% endif %}
</div>

<!-- Comment date -->
<div class="cmeta">
  <a href="#{{ m.id }}">#{{ m.id }}</a>{% include 'forum/message_admin.html' %}<br>
  {{ m.created_at|my_naturaltime }}
  {% if m.reply_to %}
   ответил <a href="{% url 'user' m.reply_to.user.id %}">{{ m.reply_to.user.username }}</a> на #{{ m.reply_to.id }}
  {% endif %}
</div>

<!-- Para -->
<div class="clearfix"></div>
{% autoescape off %}
<div class="comment-content break-word">{{ m.content }}</div>
{% endautoescape %}

forum/templates/forum/message_admin.html
{% if request.user.is_superuser and request.session.show_admin_panel %}
<span class="alert-danger admin-panel" id="message-admin-{{ m.id }}">
	<i class="fa fa-star"></i>
	<a class="btn btn-xs btn-default" href="javascript:if (confirm('Точно удалить? Удалиться вся ветка ответных сообщений!')) window.location.href='{% url 'admin_message_delete' m.id %}';" title="удалить">
	 	<i class="fa fa-close"></i>
	</a>
</span>
{% endif %}

forum/templates/forum/messages.html
{% if messages %}
	{% if messages.has_next %}
	<button onclick="show_prev(this, {{ message.id }}, {{ messages.next_page_number }})" class="btn btn-default" style="width:100%">
		Показать последние {{ messages.end_index }} из {{ messages.paginator.count }} сообщений
	</button>
	{% endif %}
	{% for m in messages.object_list %}
	{% include 'forum/message.html' %}
	{% if not forloop.last %}
	<div class="clearfix"></div>
	<hr />
	{% endif %}
	{% endfor %}
{% endif %}

forum/templates/forum/subtopics.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ title }}{% endblock %}

{% block scripts %}

<!-- intro -->
{% if request.user.is_authenticated %}
{% user_profile request.user %}
<script type="text/javascript">
var tour = MyTour('forum');
tour.addSteps([
  {
    element: "table",
    content: "Прежде всего выберите раздел форума",
    placement: 'top',
  },
  {
    element: "table",
    onShow: function() {window.location = $('a.title:first').eq(0).attr('href')+'#tour';}
  },
])
function startTour() {
  tour.init();
  tour.restart()
}
introFunc('{{ profile.looked_intro_forum }}');
</script>
{% include 'blog/profile/modal_tour.html' with text='Хотите узнать - как получать баллы за общение на форуме?' %}
{% endif %}
<!-- intro -->

{% endblock %}

{% block content %}

<div class="page-head">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>{{ title }}</h2>
        {% if description %}
        <h4>{{ description }}</h4>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<div class="content">
  <div class="container forum">
    <div class="row">
      <div class="col-md-12">

        {% breadcrumbs_block %}

        <table class="table table-bordered">
          <thead>
            <th>Топик</th>
            <th>Топики</th>
            <th>Темы</th>
            <th>Сообщения</th>
            <th>Последнее сообщение</th>
          </thead>
          {% for topic in topics %}
          <tr>
            <td>
            	<i class="fa fa-comment"></i> 
            	<a href="{% url 'forum_topic' topic.id topic.slug %}" class="title">{{ topic.title }}</a>
            </td>
            <td>{{ topic.topic_count }}</td>
            <td>{{ topic.thread_count }}</td>
            <td>{{ topic.message_count }}</td>
            <td>
            {% if topic.last_message %}
            {{ topic.last_message.user.username }}
            {{ topic.last_message.created_at|my_naturaltime }}
            {% else %}
            ---
            {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>

      </div>
    </div>
  </div>
</div>

{% endblock %}

forum/templates/forum/thread.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% load staticfiles %}

{% block scripts %}
{{ form.media }}
<style>
.comment-author .answer {
visibility:hidden;
}
.comment-author:hover .answer {
visibility:visible;
}
.comment-content img {
cursor:pointer;
}
</style>
<script>
function reply(reply_to, username) {
  $('#id_reply_to').val(reply_to);
  $('#reply_message').show().find('input').val(username + ' Сообщение #'+reply_to);
  $('html, body').animate({
      scrollTop: $('#id_content_iframe').offset().top
  }, 1000);
}
function show_prev(obj, message_id, page) {
  $.ajax({
    url: "{% url 'ajax_prev_messages' %}",
    method: "GET",
    data: {
      message_id: message_id,
      page: page,
    },
  })
  .done(function( data ) {
    if (page == 1) {
      $(obj).parent().html(data);
    }
    else {
      $(obj).replaceWith(data);
    }
  });
}

$(document).ready(function(){
  if (window.location.hash == '#tour') {
    var tour = MyTour();
    tour.addSteps([
      {
        element: "#message_form",
        content: " Создавайте свои посты",
        placement: 'top',
      },
      {
        element: ".comment-author:first",
        content: "или отвечайте другим пользователям",
        placement: 'bottom',
        onShow: function() {$('.comment-author .answer').css('visibility', 'visible');},
      },
      {
        element: "#send_button",
        content: "Пишите качественные посты и получайте призовые баллы",
        placement: 'right',
      },
    ])
    tour.init();
    tour.start(true)
    tour.goTo(0)
  }
});
</script>
{% endblock %}

{% block title %}{{ thread.title }}{% endblock %}

{% block content %}
<!-- Modal image -->
  <div class="modal fade" id="image_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Изображение</h4>
        </div>
      <div class="modal-body">
        <img id="img" src="" class="img-responsive img-thumbnail">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="page-head">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>{{ thread.title }}</h2>
      </div>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        
        {% breadcrumbs_block %}

        {% if messages %}
          <!-- Comments block -->
          <a name="comments"></a>
          <div class="comments well">
           <!-- Comment title -->
              <ul class="comment-list">
                {% for message in messages %}
                <li class="comment">
                  {% include 'forum/message.html' with m=message %}
                </li>
                
                {% if message.last_replies %}
                <li class="comment reply">
                  {% include 'forum/messages.html' with message=message messages=message.last_replies %}
                </li>
                {% endif %}

                {% endfor %}
              </ul>
              {% include 'blog/pagination.html' with list=comments %}
          </div>
          {% include 'blog/pagination.html' with list=messages %}
        {% else %}
          Нет сообщений
        {% endif %}

        {% if form %}
        {% load widget_tweaks %}
        <!-- Form Comment -->
        <div class="respond well">
        <!-- Form title -->
         <div class="title"><h4>Оставьте сообщение</h4></div>
         <!-- Comment form -->
         <div class="form">
           <form class="form-horizontal" method="post" id="message_form">
              {% csrf_token %}
              {{ form.reply_to }}
              {% if form.reply_to.errors %}<div class="alert alert-danger">{{ form.reply_to.errors }}</div>{% endif %}
               <div class="form-group" id="reply_message" style="display:none">
                 <label class="control-label col-md-3">Ответить</label>
                 <div class="col-md-9">
                   <input type="text" class="form-control" disabled="disabled">
                 </div>
               </div>
               <div class="form-group">
                 <label class="control-label col-md-3">Сообщение</label>
                 <div class="col-md-9">
                  {{ form.content }}
                  {% if form.content.errors %}<div class="alert alert-danger">{{ form.content.errors }}</div>{% endif %}
                 </div>
               </div>
               <div class="form-group">
                <div class="col-md-6 col-md-offset-3">
                 <button type="submit" class="btn btn-default" id="send_button">Отправить</button>
                 <button type="reset" class="btn btn-default">Сбросить</button>
                </div>
               </div>
           </form>
         </div>
        </div>
        {% endif %}

      </div>
    </div>
  </div>
</div>

<script>
$(function() {
  // увеличение изображений
  $('.comment-content img').on('click', function() {
    var sr=$(this).attr('src'); 
    $('#image_modal #img').attr('src',sr);
    $('#image_modal').modal('show');
  });
});
</script>
{% endblock %}

forum/templates/forum/topic.html

{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ topic.title }}{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function(){
  if (window.location.hash == '#tour') {
    var tour = MyTour();
    tour.addSteps([
      {
        element: "table",
        content: " Вы можете писать в уже созданных темах",
        placement: 'top',
      },
      {
        element: "#create_button",
        content: "Или создать свою",
        placement: 'right',
      },
      {
        element: "table",
        onShow: function() {window.location = $('a.title').eq(0).attr('href')+'#tour';}
      },
    ])
    tour.init();
    tour.start(true);
    tour.goTo(0);
  }
});
</script>
{% endblock %}

{% block content %}
<div class="page-head">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>{{ topic.title }}</h2>
      </div>
    </div>
  </div>
</div>

<div class="content">
  <div class="container forum">
    <div class="row">
      <div class="col-md-12">

        {% breadcrumbs_block %}

        <table class="table table-bordered">
          <thead>
            <th>Тема</th>
            <th>Дата создания</th>
            <th>Сообщения</th>
            <th>Последнее сообщение</th>
          </thead>
          {% for thread in threads %}
          <tr>
            <td>
              <i class="fa fa-comment"></i> 
              <a href="{% url 'forum_thread' thread.id thread.slug %}" class="title">{{ thread.title }} </a>
            </td>
            <td>{{ thread.created_at }}</td>
            <td>{{ thread.message_count }}</td>
            <td>
            {% if thread.last_message %}
            {{ thread.last_message.user.username }}
            {{ thread.last_message.created_at|my_naturaltime }}
            {% else %}
            ---
            {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
        
        {% include 'blog/pagination.html' with list=threads%}

        {% if request.user.is_authenticated %}
        <a class="btn btn-success" id="create_button" href="{% url 'forum_create_thread' topic.id %}">Создать тему</a>
        {% endif %}

      </div>
    </div>
  </div>
</div>
{% endblock %}